# Generated by Django 4.2.3 on 2023-07-07 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Контрагенты')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='VhodOstatok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('price_uch', models.FloatField(verbose_name='Цена учетная')),
                ('price_prod', models.FloatField(verbose_name='Цена продажная')),
                ('summa', models.FloatField(verbose_name='Сумма')),
                ('counterparty_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.counterparty', verbose_name='Контрагенты')),
                ('good_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.good', verbose_name='Группа товаров')),
                ('goods_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.goods', verbose_name='Товары')),
                ('measure_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.measurement', verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='ObrabotkaRashod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('price_prod', models.FloatField(verbose_name='Цена продажная')),
                ('summa', models.FloatField(verbose_name='Сумма')),
                ('doc_number', models.IntegerField(verbose_name='Номер документа')),
                ('counterparty_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.counterparty', verbose_name='Контрагенты')),
                ('good_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.good', verbose_name='Группа товаров')),
                ('goods_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.goods', verbose_name='Товары')),
                ('measure_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.measurement', verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='ObrabotkaPrihod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('price_uch', models.FloatField(verbose_name='Цена учетная')),
                ('price_prod', models.FloatField(verbose_name='Цена продажная')),
                ('summa', models.FloatField(verbose_name='Сумма')),
                ('doc_number', models.IntegerField(verbose_name='Номер документа')),
                ('counterparty_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.counterparty', verbose_name='Контрагенты')),
                ('good_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.good', verbose_name='Группа товаров')),
                ('goods_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.goods', verbose_name='Товары')),
                ('measure_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.measurement', verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='IshodRashod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('price_uch', models.FloatField(verbose_name='Цена учетная')),
                ('price_prod', models.FloatField(verbose_name='Цена продажная')),
                ('summa', models.FloatField(verbose_name='Сумма')),
                ('counterparty_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.counterparty', verbose_name='Контрагенты')),
                ('good_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.good', verbose_name='Группа товаров')),
                ('goods_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.goods', verbose_name='Товары')),
                ('measure_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.measurement', verbose_name='Единица измерения')),
            ],
        ),
    ]
