# Generated by Django 4.2.3 on 2023-07-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='total_price',
        ),
    ]
