# Generated by Django 4.2.3 on 2023-07-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_goods_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='code_number',
            field=models.CharField(max_length=4, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_number',
            field=models.CharField(max_length=4, verbose_name='Номер товара'),
        ),
    ]
