# Generated by Django 4.2.3 on 2023-07-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_goods_code_number_alter_goods_good_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название товара')),
                ('code_number', models.CharField(max_length=4, verbose_name='Код товара')),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Единица измерения')),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='code_number',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='name',
        ),
        migrations.AddField(
            model_name='goods',
            name='deliver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.deliver', verbose_name='Поставщики'),
        ),
        migrations.AddField(
            model_name='goods',
            name='good_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.good', verbose_name='Наименование товара'),
        ),
        migrations.AddField(
            model_name='goods',
            name='measure_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.measure', verbose_name='Единица измерение'),
        ),
    ]
