# Generated by Django 4.2.3 on 2023-07-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_deliver_good_measure_remove_goods_code_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='code_number',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='good_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='measure_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
