# Generated by Django 4.2.3 on 2023-07-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_goods_amount_goods_code_number_goods_good_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
