# Generated by Django 4.2.3 on 2023-08-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_goods_amount_alter_goods_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='amount',
        ),
        migrations.AddField(
            model_name='goods',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Вес'),
            preserve_default=False,
        ),
    ]
